postgres:
  host: localhost
  port: 5432
  user: postgres
  password: mysecretpassword
  dbname: tfmv


storj:
  endpoint: gateway.storjshare.io
  access_key_id: youraccesskey
  secret_access_key: yoursecretkey
  bucket_name: yourbucketname
  parquet_file_path: flights.parquet

target_table: flights_agg
